# Generated by Django 4.0 on 2021-12-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Just parking place', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_time', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('parking_place_id', models.IntegerField(null=True)),
            ],
        ),
    ]
