# Generated by Django 4.0 on 2021-12-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='ParkingPlace',
        ),
    ]
