# Generated by Django 4.0 on 2021-12-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_of_birth', models.CharField(default='', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
