# Generated by Django 4.0 on 2021-12-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_myuser_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
