# Generated by Django 4.0 on 2021-12-09 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='parkingplace',
            name='parking_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.parkingtime'),
        ),
    ]
