# Generated by Django 4.0 on 2021-12-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_parkingtime_parkingplace_parking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingtime',
            name='parking_place_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parkingtime',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
