# Generated by Django 4.0 on 2021-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_parkingtime_parking_place_id_parkingtime_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingtime',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parkingtime',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
