# Generated by Django 4.0 on 2021-12-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_parkingtime_duration_alter_parkingtime_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingplace',
            name='available',
        ),
        migrations.RemoveField(
            model_name='parkingplace',
            name='parking_time',
        ),
        migrations.RemoveField(
            model_name='parkingplace',
            name='user_id',
        ),
        migrations.AddField(
            model_name='parkingplace',
            name='descriptionn',
            field=models.CharField(default='Just parking place', max_length=50),
        ),
    ]
