# Generated by Django 4.0 on 2021-12-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_parkingplace_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingplace',
            old_name='descriptionn',
            new_name='description',
        ),
    ]
